#!/bin/sh
# Build bomberman.nes: iNES header + 32KB PRG + 32KB CHR (CNROM).
#
# Usage: build.sh [-l zh|en] [-r us|jp] [-c config/NAME.asm] [-H 1|2]
#   -l  language of the in-game text (default en)
#   -r  region of the original game the ROM is built on (default us);
#       jp builds bomberman_jp.nes from the Japanese version
#   -c  settings used by "开始游戏" / START and as the options screen
#       defaults (default config/default.asm, the original rules)
set -eu

SRC="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SRC")"
BEEBASM="${BEEBASM:-$ROOT/beebasm/beebasm}"
if [ ! -x "$BEEBASM" ]; then
  BEEBASM="$(command -v beebasm)"
fi

LANG_OPT=en
REGION=us
CONFIG=config/default.asm
HEADER=2
while getopts "l:r:c:H:" opt; do
  case "$opt" in
    l) LANG_OPT="$OPTARG" ;;
    r) REGION="$OPTARG" ;;
    c) CONFIG="$OPTARG" ;;
    H) HEADER="$OPTARG" ;;
    *) echo "Usage: $0 [-l zh|en] [-r us|jp] [-c config/NAME.asm] [-H 1|2]" >&2; exit 1 ;;
  esac
done

case "$REGION" in
  us) DEFS=""; PRG=bomberman ;;
  jp) DEFS="-D REGION_JP"; PRG=bomberman_jp ;;
  *) echo "Unknown region $REGION (expected us or jp)" >&2; exit 1 ;;
esac

cd "$SRC"

if [ ! -f "$CONFIG" ]; then
  echo "Config file not found: $CONFIG" >&2
  exit 1
fi

# Generate the CHR banks and the text data for the chosen language
python3 tools/build_text.py --lang "$LANG_OPT" --region "$REGION"

# Settings for the assembler
cat > build_config.asm <<EOF
; Generated by build.sh - do not edit
INCLUDE "$CONFIG"
EOF

case "$HEADER" in
  1) HDEFS="-D INES1=1" ;;
  2) HDEFS="" ;;
  *) echo "Unknown header $HEADER (expected 1 or 2)" >&2; exit 1 ;;
esac
"$BEEBASM" $HDEFS -i nes_header.asm
"$BEEBASM" $DEFS -i bman.asm
cat nes_header.bin $PRG bomber_text.chr > $PRG.nes

echo "ROM: $SRC/$PRG.nes ($LANG_OPT, $REGION, $CONFIG, $(wc -c < $PRG.nes | tr -d ' ') bytes)"
