#!/bin/sh
# Build bomberman.nes: iNES header + 32KB PRG + 32KB CHR (CNROM).
#
# Usage: build.sh [-l zh|en] [-c config/NAME.asm]
#   -l  language of the in-game text (default en)
#   -c  settings used by "开始游戏" / START and as the options screen
#       defaults (default config/default.asm, the original rules)
set -eu

SRC="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SRC")"
BEEBASM="${BEEBASM:-$ROOT/beebasm/beebasm}"
if [ ! -x "$BEEBASM" ]; then
  BEEBASM="$(command -v beebasm)"
fi

LANG_OPT=en
CONFIG=config/default.asm
while getopts "l:c:" opt; do
  case "$opt" in
    l) LANG_OPT="$OPTARG" ;;
    c) CONFIG="$OPTARG" ;;
    *) echo "Usage: $0 [-l zh|en] [-c config/NAME.asm]" >&2; exit 1 ;;
  esac
done

cd "$SRC"

if [ ! -f "$CONFIG" ]; then
  echo "Config file not found: $CONFIG" >&2
  exit 1
fi

# Generate the CHR banks and the text data for the chosen language
python3 tools/build_text.py --lang "$LANG_OPT"

# Settings for the assembler
cat > build_config.asm <<EOF
; Generated by build.sh - do not edit
INCLUDE "$CONFIG"
EOF

"$BEEBASM" -i nes_header.asm
"$BEEBASM" -i bman.asm
cat nes_header.bin bomberman bomber_text.chr > bomberman.nes

echo "ROM: $SRC/bomberman.nes ($LANG_OPT, $CONFIG, $(wc -c < bomberman.nes | tr -d ' ') bytes)"
