; Generated by tools/emit.py

; Call a routine in another PRG bank: JSR FAR_CALL is followed by the
; bank number and the target address - 1 (it returns there with RTS).
MACRO FARCALL bank, addr
  JSR FAR_CALL
  EQUB bank
  EQUW addr-1
ENDMACRO

; Insert n bytes of &FF (n may be 0)
MACRO PAD n
  IF n > 0
    FOR i, 1, n
      EQUB &FF
    NEXT
  ENDIF
ENDMACRO

; Pad with &FF up to addr
MACRO FILLTO addr
  ASSERT P% <= addr
  FOR n, P%, addr-1
    EQUB &FF
  NEXT
ENDMACRO

; Absolute addressing of a zero page address (BeebAsm would pick zero page)
MACRO ABS_CMP addr
  EQUB &CD
  EQUW addr
ENDMACRO

MACRO ABS_DEC addr
  EQUB &CE
  EQUW addr
ENDMACRO

MACRO ABS_INC addr
  EQUB &EE
  EQUW addr
ENDMACRO

MACRO ABS_LDA addr
  EQUB &AD
  EQUW addr
ENDMACRO

MACRO ABS_LDX addr
  EQUB &AE
  EQUW addr
ENDMACRO

MACRO ABS_LDY addr
  EQUB &AC
  EQUW addr
ENDMACRO

MACRO ABS_ORA addr
  EQUB &0D
  EQUW addr
ENDMACRO

MACRO ABS_SBC addr
  EQUB &ED
  EQUW addr
ENDMACRO

MACRO ABS_STA addr
  EQUB &8D
  EQUW addr
ENDMACRO

; Power-on stub at the end of every switchable bank. MMC1 may map any bank
; at $C000 on power-up, so each bank resets the mapper and jumps to RESET.
MACRO RESET_STUB
  EQUB &78,&D8,&A9,&10,&8D,&00,&20,&A2,&00,&BD,&D3,&FF,&9D,&00,&02,&E8
  EQUB &E0,&27,&90,&F5,&4C,&00,&02,&A9,&FF,&8D,&FF,&9F,&A9,&0E,&8D,&FF
  EQUB &9F,&4A,&8D,&FF,&9F,&4A,&8D,&FF,&9F,&4A,&8D,&FF,&9F,&4A,&8D,&FF
  EQUB &9F,&AD,&FC,&FF,&85,&00,&AD,&FD,&FF,&85,&01,&6C,&00,&00
  EQUW &FFBC, &FFBC, &FFBC
ENDMACRO
